#!/bin/bash
# Note you need to be logged into correct GCP account...
. $(dirname "$0")/ini-parser.sh

cfg.parser $(dirname "$0")/../dkr-config.ini
cfg.section.docker

echo "pushing ${image}:${version}"

docker push "${image}:${version}"