#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------
# Execute an "env" file inside the environment
# (scripts in the ~/home/env directory of the docker environment)
. $(dirname "$0")/ini-parser.sh

cfg.parser $(dirname "$0")/../dkr-config.ini

cfg.section.docker
$(dirname "$0")/dkr-exec /var/www/bin/env/"$1" "$@"
