#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------

. $(dirname "$0")/ini-parser.sh

cfg.parser $(dirname "$0")/../dkr-config.ini
cfg.section.docker

echo "building ${image}:${version}"

docker build --build-arg ARG_DOCKER_USER_ID="${uid}" --build-arg ARG_DOCKER_USER_GID="$gid" \
-t="${image}:${version}" -f ./1804-$(basename "$image" | sed s/\-//)/Dockerfile .