#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------
# Connect to the docker instance

user=www-data

if [ "$1" == '-r' ]; then
    user=root
fi

# TODO Make this smarter so we don't try to connect to an instance that doesn't exist or isn't running
# @see dkr-run
$(dirname "$0")/dkr-exec -it /bin/bash