#!/bin/bash
. $(dirname "$0")/load-config

# Create the docker network
# XXX Not needeggd at this time...
# bin/dkr-net -c

# Install the Docker image
. $(dirname "$0")/dkr-run

# Prep the filesystem
if [ !-d exports ]; then
    mkdir exports
fi

# Prepare for usage
# Notes on live-reload installation: https://magento.stackexchange.com/questions/219265/livereload-configuration-via-grunt
bin/dkr-exec -it composer install
bin/dkr-exec npm install
bin/dkr-env create-new-db.sh

echo "Installing Magento"
bin/dkr-exec bin/magento setup:install \
--base-url="$project_url" \
--db-host="$docker_mysql_host" \
--db-name="$docker_mysql_db" \
--db-user="$docker_mysql_user" \
--db-password="$docker_mysql_pw" \
--admin-firstname="$magento_admin_firstname" \
--admin-lastname="$magento_admin_lastname" \
--admin-email="$magento_admin_email" \
--admin-user="$magento_admin_user" \
--admin-password="$magento_admin_password" \
--language="$magento_language" \
--currency="$magento_currency" \
--timezone="$magento_timezone" \
--use-rewrites="$magento_use_rewrites" \
--backend-frontname="$magento_backend_frontname" \
--session-save="$magento_session_save" \
--session-save-redis-host="$docker_redis_host" \
--session-save-redis-port="$docker_redis_port" \
--session-save-redis-db="$docker_redis_session_db" \
--cache-backend="$magento_cache_backend" \
--cache-backend-redis-server="$docker_redis_host" \
--cache-backend-redis-port="$docker_redis_port" \
--cache-backend-db="$redis_cache_db" \
--page-cache="$magento_page_cache" \
--page-cache-redis-server="$docker_redis_host" \
--page-cache-redis-port="$docker_redis_port" \
--page-cache-redis-db="$docker_redis_page_cache_db"