#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------
# dkr-id [-a]
# Get the id of the currently configured container
# The -a flag will search for currently stopped containers
# The script returns 1 if the container is not found
. $(dirname "$0")/load-config

# determine if -a flag should be passed to docker ps
echo "$@" | grep '\-a' &> /dev/null

# return 1 if the container is not found
if [ $? -eq 0 ]; then
    container_id=$(docker ps -a -f name="$project_fullname" | tail -n 1 | awk '{ print $1 }')
else
    container_id=$(docker ps -f name="$project_fullname" | tail -n 1 | awk '{ print $1 }')
fi
if [ "$container_id" == "CONTAINER" ]; then
    exit 1
fi
echo "$container_id"