#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------
# Connect to the docker instance
container_id=$($(dirname "$0")/dkr-id)
if [ $? -eq 0 ]; then
    echo "not removing running container; use dkr-stop to stop it first"
    exit 1
fi

container_id=$($(dirname "$0")/dkr-id -a)
if [ $? -eq 0 ]; then
    echo "removing container"
    docker rm "$container_id"
else
    echo "no such container"
    exit 2
fi