#!/bin/bash
. $(dirname "$0")/ini-parser.sh
cfg.parser $(dirname "$0")/../dkr-config.ini
cfg.section.network

# Check for -c flag to create docker network
echo "$@" | grep '\-c' &> /dev/null
if [ $? -eq 0 ]; then
    # TODO Check if network already exists

    echo "Creating docker network $name"
    docker network create \
    --driver="$driver" \
    --subnet="$subnet" \
    --gateway="$gateway" \
    "$name"
    exit 0
fi

# Check for -rm flag to remove docker network
echo "$@" | grep '\-rm' &> /dev/null
if [ $? -eq 0 ]; then
    echo "Removing docker network $name"
    docker network rm "$name"
else
    echo "Please pass either -c or -rm flag"
    exit 1
fi