#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------
# Note you need to be logged into correct GCP account...
. $(dirname "$0")/ini-parser.sh

cfg.parser $(dirname "$0")/../dkr-config.ini
cfg.section.docker

echo "pushing ${image}:${version}"

docker push "${image}:${version}"