#!/bin/bash
container_id=$($(dirname "$0")/dkr-id)

# TODO figure out how we can pass arbitrary param through here - there's some bash syntax for it...
echo "$@" | grep '\-it' &> /dev/null
if [ $? -eq 0 ]; then
    cmd=$(echo "$@" | sed 's/-it //')
    dkr=$(which docker)
    echo "$@" | grep '\-h' &> /dev/null
    if [ $? -eq 0 ]; then
        cmd=$(echo "$@" | sed 's/-h //')
        eval "$dkr exec -u www-data -it $container_id cd /var/www && /bin/bash && $cmd"
    else
        eval "$dkr exec -u www-data -it $container_id $cmd"
    fi
else
    docker exec -u www-data "$container_id" "$@"
fi