#!/bin/bash
# load the ini parser
. $(dirname "$0")/ini-parser.sh

cfg.parser $(dirname "$0")/../config.ini
cfg.section.project

# determine if -a flag should be passed to docker ps
echo "$@" | grep '\-a' &> /dev/null

# return 1 if the container is not found
# TODO See the note in dkr-conn, in order to support that,
#      this script should support a flag to indicate wheter all containers should be listed or only running ones
if [ $? -eq 0 ]; then
    container_id=$(docker ps -a -f name="$name" | tail -n 1 | awk '{ print $1 }')
else
    container_id=$(docker ps -f name="$name" | tail -n 1 | awk '{ print $1 }')
fi
if [ "$container_id" == "CONTAINER" ]; then
    exit 1
fi
echo "$container_id"