#!/bin/bash
#-------------------------------------------------------------------------
# Copyright (c) 2017 - Moxune LLC - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Nathan Nobbe<nathan@moxune.com>
#-------------------------------------------------------------------------
# Grab the latest docker image based on configuration
. $(dirname "$0")/ini-parser.sh

cfg.parser $(dirname "$0")/../dkr-config.ini

cfg.section.docker
docker pull "$image":"$version"